using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5472
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.6.9423.0")]
[assembly: AssemblyProductAttribute("JSBSimNet")]
[assembly: AssemblyTitleAttribute("JSBSimNet Main Application")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2006, Agustin Santos Mendez")]
[assembly: AssemblyCompanyAttribute("JSBSim")]
[assembly: AssemblyTrademarkAttribute("")]

